import * as THREE from 'https://unpkg.com/three@0.179.0/build/three.module.js';
import {GAME_NAME,VERSION,BLOCK_BY_ID,ITEM_BY_ID,RECIPES,SMELTS,FUELS,DIMENSIONS,CONTROLS,WORLD_HEIGHT} from './config.js';
import {seedFromString} from './noise.js';
import {WorldManager} from './world.js';
import {InventorySystem,CraftingSystem,SmeltingSystem,StatusEffectSystem,SaveSystem,AudioManager,SignalSystem} from './systems.js';
import {EntityManager} from './entities.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fmt=n=>Number.isInteger(n)?String(n):n.toFixed(1);

class ShardwildGame{
 constructor(){
  this.container=$('#game'); this.renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.setSize(innerWidth,innerHeight);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.container.appendChild(this.renderer.domElement);
  this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.05,700);this.scene.add(this.camera);
  this.hemi=new THREE.HemisphereLight(0xbde3ff,0x32402b,1);this.sun=new THREE.DirectionalLight(0xfff2cf,1.1);this.sun.position.set(60,90,20);this.scene.add(this.hemi,this.sun);
  this.clock=new THREE.Clock();this.audio=new AudioManager();this.keys=new Set();this.mouse={left:false,right:false};this.yaw=0;this.pitch=0;this.paused=true;this.panelOpen=false;this.debug=false;this.attackCd=0;this.mine={key:null,progress:0};this.portalCd=0;this.saveTimer=0;this.blockTick=0;this.weatherTick=0;this.dayTime=.27;this.weather='clear';this.rain=null;this.messageTimer=0;this.fishingTimer=0;
  this.player={pos:new THREE.Vector3(0,35,0),vel:new THREE.Vector3(),health:20,hunger:20,xp:0,level:0,breath:10,respawn:{x:0,y:35,z:0,dimension:'overworld'},onGround:false,sprinting:false,sneaking:false,flying:false,dimension:'overworld',fallStart:null};
  this.bindUI();this.bindInput();this.renderWorldList();this.animate();
 }
 bindUI(){
  $$('.tabs button').forEach(btn=>btn.onclick=()=>{ $$('.tabs button').forEach(b=>b.classList.toggle('active',b===btn));$('#worldsTab').classList.toggle('hidden',btn.dataset.tab!=='worlds');$('#createTab').classList.toggle('hidden',btn.dataset.tab!=='create');});
  $('#createWorld').onclick=()=>{const raw=$('#worldSeed').value.trim(),seed=raw?seedFromString(raw):(Math.random()*0xffffffff)>>>0;const d=SaveSystem.create($('#worldName').value.trim()||'New Wild',seed,$('#worldMode').value);this.startWorld(d);};
  $('#resumeBtn').onclick=()=>this.resume();$('#inventoryBtn').onclick=()=>this.openInventory();$('#settingsBtn').onclick=()=>this.openSettings();$('#saveQuitBtn').onclick=()=>this.quitToTitle();$('#panelClose').onclick=()=>this.closePanel();
  $('#respawnBtn').onclick=()=>this.respawn();$('#deathQuitBtn').onclick=()=>this.quitToTitle();$('#continueBtn').onclick=()=>{ $('#victoryScreen').classList.add('hidden');this.paused=false;this.resume(); };
  addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);});
 }
 renderWorldList(){
  const list=SaveSystem.list(),root=$('#worldList');root.innerHTML='';if(!list.length)root.innerHTML='<p style="color:#91a4b4">No worlds yet. Create one to begin.</p>';
  for(const w of list){const el=document.createElement('div');el.className='world-card';const date=new Date(w.updated).toLocaleString();el.innerHTML=`<div><strong>${this.escape(w.name)}</strong><small>Seed ${w.seed} • ${w.mode} • ${date}</small></div><button class="play">Play</button><button class="delete">Delete</button>`;el.querySelector('.play').onclick=()=>{const d=SaveSystem.load(w.id);if(d)this.startWorld(d)};el.querySelector('.delete').onclick=()=>{if(confirm(`Delete ${w.name}? This cannot be undone.`)){SaveSystem.remove(w.id);this.renderWorldList();}};root.appendChild(el);}
 }
 escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
 startWorld(data){
  this.worldData=data;this.mode=data.mode||'survival';this.inv=new InventorySystem(data.player?.inventory||{});this.status=new StatusEffectSystem(data.player?.status||{});this.crafting=new CraftingSystem(this.inv);
  this.world=new WorldManager(this.scene,data.seed,data.world||{});this.signal=new SignalSystem(this.world);this.entities=new EntityManager(this.scene,this.world,{pickup:()=>this.audio.pickup(),hit:()=>this.audio.hit(),message:m=>this.showMessage(m),boss:on=>$('#bossWrap').classList.toggle('hidden',!on),bossHealth:(hp,max,protectedState,anchors)=>this.updateBossBar(hp,max,protectedState,anchors),victory:()=>this.winGame()});
  if(data.player){this.player={...this.player,...data.player,pos:new THREE.Vector3(...data.player.pos),vel:new THREE.Vector3(),respawn:data.player.respawn||this.player.respawn};this.yaw=data.player.yaw||0;this.pitch=data.player.pitch||0;this.dayTime=data.dayTime??.27;this.weather=data.weather||'clear';}
  else {const y=this.world.surfaceY(0,0,'overworld')+1;this.player.pos.set(.5,y,.5);this.player.respawn={x:.5,y,z:.5,dimension:'overworld'};if(this.mode==='creative'){['star_pick','star_sword','bow','arrow','block_28','block_29','block_41','spark_rune','echo_compass'].forEach((id,i)=>this.inv.add(id,id==='arrow'?64:1));}}
  this.player.dimension=data.player?.dimension||'overworld';this.world.setDimension(this.player.dimension);this.applyDimension(); if(data.entities)this.entities.restore(data.entities);
  $('#titleScreen').classList.remove('show');$('#hud').classList.remove('hidden');$('#pauseScreen').classList.add('hidden');$('#deathScreen').classList.add('hidden');$('#victoryScreen').classList.add('hidden');this.paused=false;this.panelOpen=false;this.lastFrame=performance.now();
  this.world.ensureAround(this.player.pos.x,this.player.pos.z);for(let i=0;i<8;i++)this.world.processQueue(2);this.updateHUD();this.showMessage(`Entered ${DIMENSIONS[this.world.dimension].name}`);this.renderer.domElement.requestPointerLock?.();
 }
 saveWorld(){if(!this.worldData||!this.world)return;this.worldData.world=this.world.exportSave();this.worldData.player={pos:this.player.pos.toArray(),health:this.player.health,hunger:this.player.hunger,xp:this.player.xp,level:this.player.level,respawn:this.player.respawn,dimension:this.world.dimension,yaw:this.yaw,pitch:this.pitch,inventory:this.inv.serialize(),status:this.status.serialize()};this.worldData.dayTime=this.dayTime;this.worldData.weather=this.weather;this.worldData.victory=!!this.worldData.victory;this.worldData.entities=this.entities.serialize();SaveSystem.save(this.worldData);}
 quitToTitle(){this.saveWorld();document.exitPointerLock?.();if(this.entities)this.entities.clear();if(this.world){for(const c of this.world.chunks.values())this.world.disposeChunk(c);this.scene.remove(this.world.group);this.scene.remove(this.world.outline);}this.worldData=null;this.world=null;this.paused=true;$('#hud').classList.add('hidden');$('#pauseScreen').classList.add('hidden');$('#panel').classList.add('hidden');$('#deathScreen').classList.add('hidden');$('#victoryScreen').classList.add('hidden');$('#titleScreen').classList.add('show');this.renderWorldList();}
 bindInput(){
  addEventListener('keydown',e=>{if(e.repeat&&['KeyE','Escape','F3','KeyC'].includes(e.code))return;this.keys.add(e.code);if(!this.worldData)return;if(e.code==='Escape'){e.preventDefault();if(this.panelOpen)this.closePanel();else if(!$('#deathScreen').classList.contains('hidden')||!$('#victoryScreen').classList.contains('hidden'))return;else this.pause();}if(e.code===CONTROLS.inventory){e.preventDefault();this.openInventory();}if(e.code===CONTROLS.debug){this.debug=!this.debug;$('#debug').classList.toggle('hidden',!this.debug);}if(e.code===CONTROLS.creative&&this.mode==='creative'){this.player.flying=!this.player.flying;this.showMessage(this.player.flying?'Flight enabled':'Flight disabled');}if(/^Digit[1-9]$/.test(e.code)){this.inv.selected=Number(e.code.slice(-1))-1;this.updateHotbar();}});
  addEventListener('keyup',e=>this.keys.delete(e.code));
  addEventListener('mousemove',e=>{if(document.pointerLockElement!==this.renderer.domElement||this.paused||this.panelOpen)return;const sens=Number(localStorage.getItem('shardwild-sensitivity')||.0022);this.yaw-=e.movementX*sens;this.pitch=clamp(this.pitch-e.movementY*sens,-Math.PI/2+.02,Math.PI/2-.02);});
  this.renderer.domElement.addEventListener('mousedown',e=>{if(!this.worldData)return;this.audio.ensure();if(document.pointerLockElement!==this.renderer.domElement&&!this.paused&&!this.panelOpen){this.renderer.domElement.requestPointerLock();return;}if(e.button===0){this.mouse.left=true;this.tryAttack();}if(e.button===2){this.mouse.right=true;this.useOrPlace();}});
  addEventListener('mouseup',e=>{if(e.button===0){this.mouse.left=false;this.mine.key=null;this.mine.progress=0;$('#mineProgress').classList.add('hidden');}if(e.button===2)this.mouse.right=false;});
  this.renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
  addEventListener('wheel',e=>{if(!this.worldData||this.panelOpen)return;this.inv.selected=(this.inv.selected+(e.deltaY>0?1:8))%9;this.updateHotbar();},{passive:true});
  document.addEventListener('pointerlockchange',()=>{document.body.classList.toggle('pointer',document.pointerLockElement===this.renderer.domElement);if(this.worldData&&!this.paused&&!this.panelOpen&&document.pointerLockElement!==this.renderer.domElement)this.pause(true);});
 }
 pause(fromUnlock=false){if(!this.worldData)return;this.paused=true;$('#pauseScreen').classList.remove('hidden');if(!fromUnlock)document.exitPointerLock?.();this.saveWorld();}
 resume(){if(!this.worldData)return;$('#pauseScreen').classList.add('hidden');$('#panel').classList.add('hidden');this.panelOpen=false;this.paused=false;this.clock.getDelta();this.renderer.domElement.requestPointerLock?.();}
 cameraDir(){const d=new THREE.Vector3(0,0,-1);d.applyEuler(new THREE.Euler(this.pitch,this.yaw,0,'YXZ'));return d.normalize();}
 updateCamera(){this.camera.position.copy(this.player.pos).add(new THREE.Vector3(0,this.player.sneaking?1.35:1.62,0));this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');}
 collides(pos){const w=.29,h=this.player.sneaking?1.45:1.78;for(let x=Math.floor(pos.x-w);x<=Math.floor(pos.x+w);x++)for(let y=Math.floor(pos.y);y<=Math.floor(pos.y+h);y++)for(let z=Math.floor(pos.z-w);z<=Math.floor(pos.z+w);z++)if(this.world.isSolidAt(x,y,z))return true;return false;}
 moveAxis(axis,amount){if(!amount)return;const step=Math.sign(amount)*Math.min(.24,Math.abs(amount));let left=Math.abs(amount);while(left>.0001){const d=Math.sign(amount)*Math.min(Math.abs(step),left),next=this.player.pos.clone();next[axis]+=d;if(!this.collides(next))this.player.pos.copy(next);else{this.player.vel[axis]=0;if(axis==='y'&&d<0)this.player.onGround=true;return false;}left-=Math.abs(d);}return true;}
 updateMovement(dt){
  const p=this.player,forward=new THREE.Vector3(-Math.sin(this.yaw),0,-Math.cos(this.yaw)),right=new THREE.Vector3(Math.cos(this.yaw),0,-Math.sin(this.yaw)),wish=new THREE.Vector3();
  if(this.keys.has(CONTROLS.forward))wish.add(forward);if(this.keys.has(CONTROLS.back))wish.sub(forward);if(this.keys.has(CONTROLS.right))wish.add(right);if(this.keys.has(CONTROLS.left))wish.sub(right);if(wish.lengthSq())wish.normalize();p.sprinting=this.keys.has(CONTROLS.sprint)&&p.hunger>3;p.sneaking=this.keys.has(CONTROLS.sneak);let speed=p.sprinting?6.2:p.sneaking?2.0:4.3;if(this.status.has('swiftness'))speed*=1.35;
  const inWater=this.world.getBlock(p.pos.x,p.pos.y+.8,p.pos.z)===58;if(inWater)speed*=.55;
  if(this.mode==='creative'&&p.flying){p.vel.y=0;if(this.keys.has(CONTROLS.jump))p.vel.y=5;if(this.keys.has(CONTROLS.sneak))p.vel.y=-5;p.vel.x=wish.x*speed*1.4;p.vel.z=wish.z*speed*1.4;}
  else {p.vel.x=THREE.MathUtils.lerp(p.vel.x,wish.x*speed,Math.min(1,dt*(p.onGround?12:4)));p.vel.z=THREE.MathUtils.lerp(p.vel.z,wish.z*speed,Math.min(1,dt*(p.onGround?12:4)));if(this.keys.has(CONTROLS.jump)&&p.onGround){p.vel.y=inWater?5.1:7.4;p.onGround=false;}p.vel.y-=DIMENSIONS[this.world.dimension].gravity*dt;if(inWater)p.vel.y=Math.max(p.vel.y,-2.2);}
  const beforeY=p.vel.y;p.onGround=false;this.moveAxis('x',p.vel.x*dt);this.moveAxis('z',p.vel.z*dt);const movedY=this.moveAxis('y',p.vel.y*dt);if(!movedY&&beforeY<0){if(beforeY<-10&&this.mode!=='creative'){const dmg=Math.max(0,Math.floor((-beforeY-9)*1.2));if(dmg)this.hurt(dmg,'a hard fall');}p.vel.y=0;}
  if(p.pos.y<-12)this.hurt(999,'the endless void');
 }
 selectedItem(){return this.inv.selectedStack();}
 toolStats(block){const s=this.selectedItem(),item=s&&ITEM_BY_ID.get(s.id);let speed=1,valid=block.tier===0;if(item?.tool===block.tool){speed=item.speed||1;valid=(item.tier||0)>=block.tier;}if(this.mode==='creative')return {speed:999,valid:true};return {speed,valid,item};}
 tryAttack(){if(this.paused||this.panelOpen||this.attackCd>0)return;const dir=this.cameraDir(),s=this.selectedItem(),it=s&&ITEM_BY_ID.get(s.id),damage=it?.damage||1;if(this.entities.melee(this.camera.position,dir,damage+(s?.ench?.power||0),this)){this.attackCd=it?.type==='weapon'?.45:.7;this.inv.damageSelected(1);this.updateHotbar();}}
 updateMining(dt){if(!this.mouse.left||this.paused||this.panelOpen)return;const hit=this.world.updateSelection(this.camera.position,this.cameraDir(),6);if(!hit){this.mine.key=null;return;}const b=BLOCK_BY_ID.get(hit.id);if(!b||b.hardness<0)return;const key=`${hit.x},${hit.y},${hit.z}`;if(this.mine.key!==key){this.mine.key=key;this.mine.progress=0;}const tool=this.toolStats(b);this.mine.progress+=dt*tool.speed/Math.max(.12,b.hardness);$('#mineProgress').classList.remove('hidden');$('#mineProgress i').style.width=`${Math.min(100,this.mine.progress*100)}%`;if(this.mine.progress>=1){this.breakBlock(hit,tool.valid);this.mine.key=null;this.mine.progress=0;$('#mineProgress').classList.add('hidden');}}
 breakBlock(hit,valid){const b=BLOCK_BY_ID.get(hit.id);this.world.setBlock(hit.x,hit.y,hit.z,0);this.audio.break();if(this.mode!=='creative'&&valid&&b.drop!==null){let id=typeof b.drop==='number'?`block_${b.drop}`:b.drop;if(hit.id===6&&Math.random()<.22)id='flint';this.entities.dropItem(id,1,new THREE.Vector3(hit.x+.5,hit.y+.3,hit.z+.5));if(hit.id===1&&Math.random()<.18)this.entities.dropItem('grain_seed',1,new THREE.Vector3(hit.x+.5,hit.y+.5,hit.z+.5));}if(this.mode!=='creative')this.inv.damageSelected(1);if(hit.id===86)this.showMessage('A Void Anchor shatters. The Regent weakens.');if(hit.id===65)this.explode(new THREE.Vector3(hit.x+.5,hit.y+.5,hit.z+.5),4,8);this.updateHotbar();}
 useOrPlace(){
  if(this.paused||this.panelOpen)return;const hit=this.world.updateSelection(this.camera.position,this.cameraDir(),6),s=this.selectedItem(),it=s&&ITEM_BY_ID.get(s.id);if(hit){const id=hit.id;
   if(id===28){this.openInventory(true);return;}if(id===29){this.openFurnace(hit.x,hit.y,hit.z);return;}if(id===30){this.openContainer(hit.x,hit.y,hit.z);return;}if(id===67){this.openUpgrade();return;}if(id===68){this.openBrewery();return;}if(id===69){this.player.respawn={x:hit.x+.5,y:hit.y+1,z:hit.z+.5,dimension:this.world.dimension};this.showMessage('Respawn point set.');return;}if(id===51){const on=this.signal.toggleLever(hit.x,hit.y,hit.z);this.showMessage(`Pulse lever ${on?'ON':'OFF'}`);return;}
   if(id===48&&this.inv.has('void_sigil',4)){if(this.world.activateEndgate(hit,4)){this.inv.remove('void_sigil',4);this.showMessage('The Aether Gate awakens.');this.audio.portal();this.updateHotbar();return;}}
   if(s?.id==='spark_rune'&&id===41){if(this.world.activatePortal(hit,'spark_rune')){if(this.mode!=='creative')this.inv.remove('spark_rune',1);this.showMessage('A Cinder Rift tears open.');this.audio.portal();this.updateHotbar();return;}}
   if(it?.type==='tool'&&it.tool==='hoe'&&(id===1||id===2)){this.world.setBlock(hit.x,hit.y,hit.z,32);this.inv.damageSelected(1);this.audio.place();return;}
   if(s?.id==='grain_seed'&&id===32&&!this.world.getBlock(hit.x,hit.y+1,hit.z)){this.world.setBlock(hit.x,hit.y+1,hit.z,33);if(this.mode!=='creative')this.inv.remove('grain_seed',1);this.audio.place();this.updateHotbar();return;}
  }
  if(it?.food){this.consumeFood(s,it);return;}if(it?.type==='potion'){this.drinkPotion(s);return;}if(s?.id==='fishing_rod'){this.startFishing();return;}if(it?.type==='ranged'&&s.id==='bow'){this.fireBow();return;}
  if(hit&&it?.block){const p=hit.prev;if(this.canPlaceAt(p.x,p.y,p.z)){this.world.setBlock(p.x,p.y,p.z,it.block);if(this.mode!=='creative')this.inv.remove(s.id,1);this.audio.place();this.updateHotbar();}}
 }
 canPlaceAt(x,y,z){if(this.world.getBlock(x,y,z))return false;const pp=this.player.pos;return !(Math.abs(pp.x-(x+.5))<.7&&Math.abs(pp.z-(z+.5))<.7&&pp.y<y+1&&pp.y+1.8>y);}
 consumeFood(s,it){if(this.player.hunger>=20)return;this.player.hunger=Math.min(20,this.player.hunger+it.food);if(this.mode!=='creative')this.inv.remove(s.id,1);this.audio.tone(220,.08,'square',.03);this.updateHUD();}
 drinkPotion(s){if(s.id==='healing_draught')this.player.health=Math.min(20,this.player.health+8);if(s.id==='swiftness_draught')this.status.add('swiftness',120);if(s.id==='fireward_draught')this.status.add('fireward',180);if(this.mode!=='creative')this.inv.remove(s.id,1);this.updateHUD();}
 startFishing(){if(this.fishingTimer>0){this.showMessage('Line already cast.');return;}const hit=this.world.raycast(this.camera.position,this.cameraDir(),8);if(!hit||hit.id!==58){this.showMessage('Cast toward open water.');return;}this.fishingTimer=2.5+Math.random()*4;this.showMessage('Line cast…');}
 fireBow(){if(this.attackCd>0||(!this.inv.has('arrow',1)&&this.mode!=='creative'))return;if(this.mode!=='creative')this.inv.remove('arrow',1);this.entities.firePlayerProjectile(this.camera.position.clone(),this.cameraDir(),7+(this.selectedItem()?.ench?.power||0));this.inv.damageSelected(1);this.attackCd=.6;this.audio.tone(300,.06,'triangle',.04);this.updateHotbar();}
 updateSurvival(dt){
  if(this.mode==='creative')return;const p=this.player;this.hungerClock=(this.hungerClock||0)+dt*(p.sprinting?2:1);if(this.hungerClock>10){this.hungerClock=0;p.hunger=Math.max(0,p.hunger-1);}if(p.hunger>=17&&p.health<20){this.regenClock=(this.regenClock||0)+dt;if(this.regenClock>4){this.regenClock=0;p.health=Math.min(20,p.health+1);p.hunger=Math.max(0,p.hunger-.5);}}else this.regenClock=0;if(p.hunger<=0){this.starveClock=(this.starveClock||0)+dt;if(this.starveClock>5){this.starveClock=0;this.hurt(1,'starvation');}}
  const head=this.world.getBlock(p.pos.x,p.pos.y+1.55,p.pos.z),feet=this.world.getBlock(p.pos.x,p.pos.y+.25,p.pos.z);if(head===58){p.breath-=dt;if(p.breath<=0){p.breath=0;this.drownClock=(this.drownClock||0)+dt;if(this.drownClock>1.2){this.drownClock=0;this.hurt(2,'drowning');}}}else p.breath=Math.min(10,p.breath+dt*2);
  if(BLOCK_BY_ID.get(head)?.solid)this.hurtTick('suffocation',dt,1,1);if(feet===59||head===59){if(!this.status.has('fireward'))this.hurtTick('lava',dt,4,.65);} }
 hurtTick(key,dt,dmg,interval){this.damageTimers=this.damageTimers||{};this.damageTimers[key]=(this.damageTimers[key]||0)+dt;if(this.damageTimers[key]>=interval){this.damageTimers[key]=0;this.hurt(dmg,key);}}
 hurt(amount,reason='danger'){
  if(this.mode==='creative'||this.player.health<=0)return;let armor=this.inv.armorPoints(),reduced=amount*(1-Math.min(.72,armor*.035));if(this.mouse.right&&this.inv.equipment.shield)reduced*=.35;this.player.health-=Math.max(.5,reduced);this.audio.hit();if(this.player.health<=0){this.player.health=0;this.die(reason);}this.updateHUD();}
 die(reason){document.exitPointerLock?.();this.paused=true;for(let i=0;i<this.inv.slots.length;i++){const s=this.inv.slots[i];if(s){this.entities.dropItem(s.id,s.count,this.player.pos.clone());this.inv.slots[i]=null;}}$('#deathReason').textContent=`Cause: ${reason}`;$('#deathScreen').classList.remove('hidden');this.saveWorld();}
 respawn(){const r=this.player.respawn;if(r.dimension!==this.world.dimension){this.changeDimension(r.dimension,new THREE.Vector3(r.x,r.y,r.z));}else this.player.pos.set(r.x,r.y,r.z);this.player.vel.set(0,0,0);this.player.health=20;this.player.hunger=20;this.player.breath=10;$('#deathScreen').classList.add('hidden');this.paused=false;this.resume();}
 addXp(n){this.player.xp+=n;while(this.player.xp>=this.xpForNext()){this.player.xp-=this.xpForNext();this.player.level++;this.audio.tone(720,.15,'sine',.04);this.showMessage(`Level ${this.player.level}`);}this.updateHUD();}
 xpForNext(){return 8+this.player.level*4;}
 explode(pos,radius,damage){
  this.audio.noise(.3,.1);for(let x=Math.floor(pos.x-radius);x<=Math.ceil(pos.x+radius);x++)for(let y=Math.floor(pos.y-radius);y<=Math.ceil(pos.y+radius);y++)for(let z=Math.floor(pos.z-radius);z<=Math.ceil(pos.z+radius);z++){const d=Math.hypot(x+.5-pos.x,y+.5-pos.y,z+.5-pos.z);if(d>radius||Math.random()>1-d/radius*.55)continue;const id=this.world.getBlock(x,y,z),b=BLOCK_BY_ID.get(id);if(id&&b?.hardness>=0&&b.hardness<5)this.world.setBlock(x,y,z,0);}
  const pd=this.player.pos.distanceTo(pos);if(pd<radius*1.5)this.hurt(Math.max(1,damage*(1-pd/(radius*1.5))),'an explosion');for(const m of this.entities.mobs){const d=m.group.position.distanceTo(pos);if(d<radius*1.5)this.entities.damageMob(m,Math.max(1,damage*(1-d/(radius*1.5))),this);}
 }
 checkPortals(){
  if(this.portalCd>0)return;const id=this.world.getBlock(this.player.pos.x,this.player.pos.y+.5,this.player.pos.z);if(id===42){const from=this.world.dimension,to=from==='overworld'?'infernal':'overworld',scale=from==='overworld'?1/8:8;const x=Math.round(this.player.pos.x*scale),z=Math.round(this.player.pos.z*scale),y=this.safeY(to,x,z);this.portalCd=4;this.audio.portal();this.changeDimension(to,new THREE.Vector3(x+.5,y,z+.5),true);}
  else if(id===49&&this.world.dimension==='overworld'){this.portalCd=4;this.audio.portal();this.changeDimension('void',new THREE.Vector3(.5,28,.5),true);}
  else if(id===49&&this.world.dimension==='void'&&this.worldData.victory){this.portalCd=4;this.changeDimension('overworld',new THREE.Vector3(this.world.structureInfo.stronghold.x+.5,16,this.world.structureInfo.stronghold.z+.5),true);}
 }
 safeY(dim,x,z){if(dim==='overworld')return this.world.surfaceY(x,z,dim)+1;for(let y=10;y<WORLD_HEIGHT-4;y++)if(this.world.generatedBlock(dim,x,y-1,z)&&!this.world.generatedBlock(dim,x,y,z)&&!this.world.generatedBlock(dim,x,y+1,z))return y;return dim==='infernal'?20:28;}
 createSafeRift(){
  const x=Math.floor(this.player.pos.x)+2,z=Math.floor(this.player.pos.z),y=Math.max(3,Math.floor(this.player.pos.y));for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)this.world.setBlock(x+dx,y-1,z+dz,this.world.dimension==='infernal'?36:3);for(let w=0;w<4;w++)for(let h=0;h<5;h++){const edge=w===0||w===3||h===0||h===4;this.world.setBlock(x+w,y+h,z,edge?41:42);} }
 changeDimension(to,pos,ensurePortal=false){
  this.entities.clear();this.world.setDimension(to);this.player.dimension=to;this.player.pos.copy(pos);this.player.vel.set(0,0,0);this.applyDimension();this.world.ensureAround(pos.x,pos.z);for(let i=0;i<6;i++)this.world.processQueue(2);if(ensurePortal&&to!=='void')this.createSafeRift();this.showMessage(`Entered ${DIMENSIONS[to].name}`);this.updateObjective();
 }
 applyDimension(){const d=DIMENSIONS[this.world.dimension];this.scene.background=new THREE.Color(d.sky);this.scene.fog=new THREE.FogExp2(d.fog,this.world.dimension==='overworld'?.007:.012);this.hemi.intensity=d.ambient;this.sun.intensity=this.world.dimension==='overworld'?1:.32;}
 updateDayNight(dt){
  if(this.world.dimension!=='overworld'){this.dayLight=.35;return;}this.dayTime=(this.dayTime+dt/720)%1;const a=this.dayTime*Math.PI*2,day=clamp(Math.sin(a)*.55+.55,.08,1);this.dayLight=day;this.sun.position.set(Math.cos(a)*90,Math.sin(a)*120,35);this.sun.intensity=.12+day*1.1;this.hemi.intensity=.22+day*.65;const sky=new THREE.Color(0x0b1430).lerp(new THREE.Color(0x87b8e6),day);this.scene.background=sky;this.scene.fog.color.copy(sky);
  this.weatherTick-=dt;if(this.weatherTick<=0){this.weatherTick=60+Math.random()*120;if(Math.random()<.28)this.weather=this.weather==='clear'?'rain':'clear';}this.updateRain(dt);
 }
 updateRain(dt){if(this.world.dimension!=='overworld'||this.weather!=='rain'){if(this.rain)this.rain.visible=false;return;}if(!this.rain){const count=500,arr=new Float32Array(count*3);for(let i=0;i<count;i++){arr[i*3]=(Math.random()-.5)*42;arr[i*3+1]=Math.random()*30;arr[i*3+2]=(Math.random()-.5)*42;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(arr,3));const m=new THREE.PointsMaterial({color:0xbad6e6,size:.06,transparent:true,opacity:.65});this.rain=new THREE.Points(g,m);this.scene.add(this.rain);}this.rain.visible=true;this.rain.position.set(this.player.pos.x,Math.floor(this.player.pos.y),this.player.pos.z);const a=this.rain.geometry.attributes.position.array;for(let i=0;i<a.length;i+=3){a[i+1]-=dt*18;if(a[i+1]<0)a[i+1]=30;}this.rain.geometry.attributes.position.needsUpdate=true;}
 updateEnvironment(dt){
  this.status.tick(dt);this.portalCd=Math.max(0,this.portalCd-dt);this.attackCd=Math.max(0,this.attackCd-dt);this.blockTick+=dt;if(this.blockTick>.6){this.blockTick=0;this.world.tickBlocks(this.player.pos);for(const be of Object.values(this.world.blockEntities))if(be?.type==='furnace')SmeltingSystem.tick(be,.6);}
  if(this.fishingTimer>0){this.fishingTimer-=dt;if(this.fishingTimer<=0){const count=1+(Math.random()<.2?1:0);this.entities.dropItem('raw_fish',count,this.player.pos.clone().add(this.cameraDir().multiplyScalar(1.2)));this.showMessage('Something bites!');this.inv.damageSelected(1);}}
  this.checkPortals();this.updateSurvival(dt);this.updateDayNight(dt);
 }
 updateObjective(){if(!this.worldData)return;let msg='';if(this.worldData.victory)msg='Sandbox unlocked • explore, build, automate, and return between realms.';else if(!this.inv.has('wood_pick')&&!this.inv.has('stone_pick')&&!this.inv.has('iron_pick')&&!this.inv.has('star_pick'))msg='Objective: gather Oakheart wood → craft planks, rods, a bench, and your first pick.';else if(!this.inv.has('iron_ingot',3)&&!this.inv.has('iron_pick'))msg='Objective: mine stone and iron ore → build a Kiln Furnace → smelt Iron Ingots.';else if(!this.inv.has('spark_rune')&&this.world.dimension==='overworld')msg='Objective: mine Azurite + iron → craft a Spark Rune and Rift Frames at a Crafting Bench.';else if(this.world.dimension==='overworld'&&!this.inv.has('ember_core'))msg='Objective: build a 4×5 Rift Frame rectangle, ignite it with the Spark Rune, enter Cinderdeep.';else if(this.world.dimension==='infernal'&&!this.inv.has('ember_core'))msg=`Objective: seek the Cinderdeep fortress near ${this.world.structureInfo.infernalFort.x}, ${this.world.structureInfo.infernalFort.z}; defeat Brimstalkers for an Ember Core.`;else if(!this.inv.has('echo_compass')&&!this.inv.has('void_sigil',4))msg='Objective: return to the Reach. Craft an Echo Compass and four Void Sigils from Cinder resources.';else if(this.world.dimension==='overworld')msg=`Objective: follow the Echo Compass to the Ancient Aster Keep near ${this.world.structureInfo.stronghold.x}, ${this.world.structureInfo.stronghold.z}; awaken its gate with 4 Void Sigils.`;else if(this.world.dimension==='void')msg='Objective: shatter the four glowing Void Anchors, then defeat the Hollow Regent.';$('#objective').textContent=msg;}
 updateBossBar(hp,max,protectedState,anchors){$('#bossWrap').classList.remove('hidden');$('#bossFill').style.width=`${Math.max(0,hp/max*100)}%`;$('#bossState').textContent=protectedState?`WARD SHIELD ACTIVE • ${anchors} anchor${anchors===1?'':'s'} remain`:'WARD SHIELD BROKEN';}
 winGame(){this.worldData.victory=true;this.addXp(120);for(let x=-1;x<=1;x++)for(let z=-1;z<=1;z++)this.world.setBlock(x,26,z,49);this.saveWorld();this.audio.victory();document.exitPointerLock?.();this.paused=true;$('#victoryScreen').classList.remove('hidden');$('#bossWrap').classList.add('hidden');}
 showMessage(text){const el=$('#message');el.textContent=text;el.style.opacity='1';this.messageTimer=2.6;}
 openPanel(title){this.panelWasPaused=this.paused;this.paused=true;this.panelOpen=true;document.exitPointerLock?.();$('#pauseScreen').classList.add('hidden');$('#panelTitle').textContent=title;$('#panel').classList.remove('hidden');}
 closePanel(){if(!this.panelOpen)return;$('#panel').classList.add('hidden');this.panelOpen=false;if(this.panelWasPaused){this.paused=true;$('#pauseScreen').classList.remove('hidden');}else this.resume();}
 itemLabel(stack){if(!stack)return '';const it=ITEM_BY_ID.get(stack.id);return it?.name||stack.id;}
 slotHTML(stack,index,selected=false){if(!stack)return `<button class="slot ${selected?'selected':''}" data-slot="${index}"></button>`;const it=ITEM_BY_ID.get(stack.id),dur=it?.durability?Math.round(((stack.durability??it.durability)/it.durability)*100):null;return `<button class="slot ${selected?'selected':''}" data-slot="${index}" title="${this.escape(it?.name||stack.id)}"><span class="name">${this.escape(it?.name||stack.id)}</span>${stack.count>1?`<span class="count">${stack.count}</span>`:''}${dur!==null?`<span class="dur"><i style="width:${dur}%"></i></span>`:''}${stack.ench?'<span style="position:absolute;top:2px;right:3px;color:#b8a4ff">✦</span>':''}</button>`;}
 openInventory(bench=false){this.openPanel(bench?'Crafting Bench':'Inventory & Personal Crafting');this.currentInventoryBench=bench;this.renderInventoryPanel();}
 renderInventoryPanel(){
  const bench=this.currentInventoryBench,body=$('#panelBody');let html='<div class="equipment">';for(const k of ['head','chest','legs','feet','shield']){const s=this.inv.equipment[k];html+=`<button class="equip" data-equip="${k}"><small>${k.toUpperCase()}</small><br>${s?this.escape(this.itemLabel(s)):'—'}</button>`;}html+='</div><div class="grid">';for(let i=0;i<36;i++)html+=this.slotHTML(this.inv.slots[i],i,i===this.inv.selected);html+='</div>';
  const available=this.crafting.available(bench).map(r=>r.id);html+=`<h3>${bench?'3×3 Bench Recipes':'2×2 Personal Recipes'}</h3><div class="recipe-list">`;for(const r of RECIPES){const allowed=available.includes(r.id),ingredients=r.in.map(([id,n])=>`${n} ${ITEM_BY_ID.get(id)?.name||id}`).join(' + ');if(!bench&&!['planks','sticks','bench','crate','furnace','torch','wood_pick','stone_pick','stone_sword','bread','rod','pulse_lever'].includes(r.id))continue;html+=`<button class="recipe" data-recipe="${r.id}" ${allowed?'':'disabled'}><b>${this.escape(r.name)}</b><small>${this.escape(ingredients)}</small></button>`;}html+='</div>';
  if(this.mode==='creative'){html+='<h3>Creative Catalog</h3><div class="action-list">';for(const it of [...ITEM_BY_ID.values()].slice(0,140))html+=`<button data-give="${it.id}">${this.escape(it.name)}</button>`;html+='</div>';}
  body.innerHTML=html;body.querySelectorAll('[data-slot]').forEach(btn=>{btn.onclick=e=>this.inventorySlotClick(Number(btn.dataset.slot),e.shiftKey);btn.oncontextmenu=e=>{e.preventDefault();this.splitStack(Number(btn.dataset.slot));};});body.querySelectorAll('[data-equip]').forEach(btn=>btn.onclick=()=>{const k=btn.dataset.equip,s=this.inv.equipment[k];if(s){this.inv.equipment[k]=null;this.inv.add(s.id,1,s);this.renderInventoryPanel();}});body.querySelectorAll('[data-recipe]').forEach(btn=>btn.onclick=()=>{if(this.crafting.craft(btn.dataset.recipe,bench)){this.audio.ui();this.renderInventoryPanel();this.updateHUD();}});body.querySelectorAll('[data-give]').forEach(btn=>btn.onclick=()=>{this.inv.add(btn.dataset.give,ITEM_BY_ID.get(btn.dataset.give)?.stack===1?1:64);this.renderInventoryPanel();this.updateHUD();});
 }
 inventorySlotClick(i,shift){if(shift){if(this.inv.equipFrom(i)){this.renderInventoryPanel();this.updateHUD();return;}}if(this.uiHeld==null){if(!this.inv.slots[i])return;this.uiHeld=i;}else{this.inv.move(this.uiHeld,i,false);this.uiHeld=null;}this.renderInventoryPanel();this.updateHUD();}
 splitStack(i){const s=this.inv.slots[i];if(!s||s.count<2)return;const empty=this.inv.slots.findIndex(x=>!x);if(empty<0)return;this.inv.move(i,empty,true);this.renderInventoryPanel();this.updateHUD();}
 openContainer(x,y,z){this.openPanel('Crate Storage');const key=`${this.world.dimension}:${x},${y},${z}`,be=this.world.blockEntities[key]||(this.world.blockEntities[key]={type:'crate',items:Array(27).fill(null)});if(!be.items)be.items=Array(27).fill(null);this.containerEntity=be;this.renderContainer();}
 transferInto(slots,stack){if(!stack)return false;const it=ITEM_BY_ID.get(stack.id),limit=it?.stack||64;for(const s of slots){if(s&&s.id===stack.id&&s.count<limit){const n=Math.min(stack.count,limit-s.count);s.count+=n;stack.count-=n;if(stack.count<=0)return true;}}for(let i=0;i<slots.length;i++)if(!slots[i]){slots[i]={...stack};stack.count=0;return true;}return stack.count<=0;}
 renderContainer(){
  const be=this.containerEntity,body=$('#panelBody');let html='<div class="split"><div><h3>Crate</h3><div class="container-grid">';for(let i=0;i<27;i++){const s=be.items[i];html+=`<button data-cslot="${i}">${s?this.escape(this.itemLabel(s))+(s.count>1?' ×'+s.count:''):'—'}</button>`;}html+='</div></div><div><h3>Inventory</h3><div class="container-grid">';for(let i=0;i<36;i++){const s=this.inv.slots[i];html+=`<button data-islot="${i}">${s?this.escape(this.itemLabel(s))+(s.count>1?' ×'+s.count:''):'—'}</button>`;}html+='</div></div></div><p><small>Click an item to transfer it between inventory and crate. Stack merging is automatic.</small></p>';body.innerHTML=html;
  body.querySelectorAll('[data-islot]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.islot),s=this.inv.slots[i];if(!s)return;const tmp={...s};if(this.transferInto(be.items,tmp)){this.inv.slots[i]=null;}else this.inv.slots[i]={...tmp};this.renderContainer();this.updateHUD();});
  body.querySelectorAll('[data-cslot]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.cslot),s=be.items[i];if(!s)return;const left=this.inv.add(s.id,s.count,s);if(left<=0)be.items[i]=null;else s.count=left;this.renderContainer();this.updateHUD();});
 }
 openFurnace(x,y,z){this.openPanel('Kiln Furnace');this.furnace=SmeltingSystem.getEntity(this.world,x,y,z);this.renderFurnace();}
 renderFurnace(){
  const f=this.furnace,body=$('#panelBody'),inName=f.input?`${this.itemLabel(f.input)} ×${f.input.count}`:'Empty',fuelName=f.fuel?`${this.itemLabel(f.fuel)} ×${f.fuel.count}`:'Empty',outName=f.output?`${this.itemLabel(f.output)} ×${f.output.count}`:'Empty';body.innerHTML=`<div class="split"><div><h3>Furnace</h3><p>Input: <b>${this.escape(inName)}</b></p><p>Fuel: <b>${this.escape(fuelName)}</b></p><p>Output: <b>${this.escape(outName)}</b></p><p>Burn: ${Math.max(0,f.burn).toFixed(1)}s • Progress: ${f.progress.toFixed(1)}s</p><div class="action-list"><button id="fInput">Load selected as input</button><button id="fFuel">Load selected as fuel</button><button id="fOut">Take output</button></div></div><div><h3>Hotbar</h3><div class="container-grid">${Array.from({length:9},(_,i)=>`<button data-select="${i}">${this.inv.slots[i]?this.escape(this.itemLabel(this.inv.slots[i]))+' ×'+this.inv.slots[i].count:'—'}</button>`).join('')}</div></div></div>`;
  body.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{this.inv.selected=Number(b.dataset.select);this.renderFurnace();this.updateHotbar();});$('#fInput').onclick=()=>{const s=this.selectedItem();if(!s||!SMELTS[s.id])return;f.input=this.mergeMachineSlot(f.input,s);this.renderFurnace();this.updateHUD();};$('#fFuel').onclick=()=>{const s=this.selectedItem();if(!s||!FUELS[s.id])return;f.fuel=this.mergeMachineSlot(f.fuel,s);this.renderFurnace();this.updateHUD();};$('#fOut').onclick=()=>{if(!f.output)return;const left=this.inv.add(f.output.id,f.output.count,f.output);if(left<=0)f.output=null;else f.output.count=left;this.renderFurnace();this.updateHUD();};
 }
 mergeMachineSlot(target,source){const it=ITEM_BY_ID.get(source.id),limit=it?.stack||64;if(target&&target.id!==source.id)return target;let n=target?.count||0,take=Math.min(source.count,limit-n);const out=target||{...source,count:0};out.count+=take;source.count-=take;if(source.count<=0)this.inv.slots[this.inv.selected]=null;return out;}
 openUpgrade(){this.openPanel('Rune Table');this.renderUpgrade();}
 renderUpgrade(){const s=this.selectedItem(),it=s&&ITEM_BY_ID.get(s.id),valid=it&&['tool','weapon','ranged'].includes(it.type);$('#panelBody').innerHTML=`<p>Selected: <b>${s?this.escape(this.itemLabel(s)):'none'}</b></p><p>Current rune power: ${s?.ench?.power||0}</p><p>Cost: 3 levels + 2 Azurite. Each rune rank adds damage and mining power.</p><button id="upgradeItem" class="primary" ${valid&&this.player.level>=3&&this.inv.has('azurite',2)?'':'disabled'}>Inscribe selected item</button>`;$('#upgradeItem').onclick=()=>{if(!valid||this.player.level<3||!this.inv.has('azurite',2))return;this.player.level-=3;this.inv.remove('azurite',2);s.ench={power:(s.ench?.power||0)+1};this.audio.tone(840,.35,'sine',.05);this.renderUpgrade();this.updateHUD();};}
 openBrewery(){this.openPanel('Brewery');const recipes=[['healing_draught','Mending Draught',[['glowcap',1],['azurite',1]]],['swiftness_draught','Gale Draught',[['glowcap',1],['reed',2],['azurite',1]]],['fireward_draught','Cinderward Draught',[['glowcap',1],['ember_crystal',1]]]];$('#panelBody').innerHTML='<p>Brew original alchemical draughts from gathered reagents.</p><div class="action-list">'+recipes.map(([id,n,ins])=>`<button data-brew="${id}" ${ins.every(([i,c])=>this.inv.has(i,c))?'':'disabled'}><b>${n}</b><br><small>${ins.map(([i,c])=>`${c} ${ITEM_BY_ID.get(i)?.name||i}`).join(' + ')}</small></button>`).join('')+'</div>';$('#panelBody').querySelectorAll('[data-brew]').forEach(btn=>btn.onclick=()=>{const r=recipes.find(x=>x[0]===btn.dataset.brew);if(r&&this.inv.consumeMany(r[2])){this.inv.add(r[0],1);this.audio.ui();this.openBrewery();this.updateHUD();}});}
 openSettings(){this.openPanel('Settings');const rd=this.world?.renderDistance||3,fov=this.camera.fov,sens=Number(localStorage.getItem('shardwild-sensitivity')||.0022),vol=this.audio.master;$('#panelBody').innerHTML=`<div class="setting"><label>FOV</label><input id="sFov" type="range" min="60" max="100" value="${fov}"><span>${fov}</span></div><div class="setting"><label>Mouse sensitivity</label><input id="sSens" type="range" min="0.001" max="0.005" step="0.0001" value="${sens}"><span>${sens}</span></div><div class="setting"><label>Render distance</label><input id="sRender" type="range" min="2" max="6" value="${rd}"><span>${rd} chunks</span></div><div class="setting"><label>Master volume</label><input id="sVolume" type="range" min="0" max="1" step="0.05" value="${vol}"><span>${Math.round(vol*100)}%</span></div><div class="setting"><label>Resolution scale</label><select id="sScale"><option value="1">Performance</option><option value="1.5">Quality</option></select><span></span></div><p><small>Controls: WASD move • mouse look • Space jump • Shift sprint • Ctrl sneak • E inventory • 1–9 hotbar • left mine/attack • right use/place • F3 debug • C creative flight.</small></p>`;
  const update=(id,fn,format=v=>v)=>{const el=$(id),span=el.parentElement.querySelector('span');el.oninput=()=>{fn(el.value);span.textContent=format(el.value);};};update('#sFov',v=>{this.camera.fov=Number(v);this.camera.updateProjectionMatrix();});update('#sSens',v=>localStorage.setItem('shardwild-sensitivity',v));update('#sRender',v=>{this.world.renderDistance=Number(v);this.world.lastCenter='';},v=>`${v} chunks`);update('#sVolume',v=>this.audio.master=Number(v),v=>`${Math.round(v*100)}%`);$('#sScale').onchange=e=>{this.renderer.setPixelRatio(Number(e.target.value));this.renderer.setSize(innerWidth,innerHeight);};
 }
 updateHotbar(){const root=$('#hotbar');root.innerHTML='';for(let i=0;i<9;i++){const wrap=document.createElement('div');wrap.innerHTML=this.slotHTML(this.inv.slots[i],i,i===this.inv.selected);root.appendChild(wrap.firstChild);} }
 updateHUD(){if(!this.inv)return;$('#healthBar').style.width=`${clamp(this.player.health/20*100,0,100)}%`;$('#healthText').textContent=fmt(Math.max(0,this.player.health));$('#hungerBar').style.width=`${clamp(this.player.hunger/20*100,0,100)}%`;$('#hungerText').textContent=fmt(this.player.hunger);const armor=this.inv.armorPoints();$('#armorBar').style.width=`${clamp(armor/20*100,0,100)}%`;$('#armorText').textContent=armor;$('#xpBar').style.width=`${clamp(this.player.xp/this.xpForNext()*100,0,100)}%`;$('#xpText').textContent=`Lv ${this.player.level}`;this.updateHotbar();this.updateObjective();}
 updateDebug(){if(!this.debug||!this.world)return;const b=this.world.biomeAt(Math.floor(this.player.pos.x),Math.floor(this.player.pos.z));$('#debug').innerHTML=`${GAME_NAME} ${VERSION}<br>XYZ ${this.player.pos.x.toFixed(1)} / ${this.player.pos.y.toFixed(1)} / ${this.player.pos.z.toFixed(1)}<br>Realm ${DIMENSIONS[this.world.dimension].name}<br>Biome ${b.name}<br>Chunks ${this.world.chunks.size} • Queue ${this.world.queue.length}<br>Entities ${this.entities.mobs.length} • Drops ${this.entities.drops.length}<br>Time ${(this.dayTime*24).toFixed(1)}h • ${this.weather}<br>Seed ${this.world.seed}`;}
 animate(){requestAnimationFrame(()=>this.animate());const dt=Math.min(.05,this.clock.getDelta());if(this.messageTimer>0){this.messageTimer-=dt;if(this.messageTimer<=0)$('#message').style.opacity='0';}if(this.worldData&&this.world&&!this.paused&&!this.panelOpen){this.updateMovement(dt);this.updateCamera();this.world.ensureAround(this.player.pos.x,this.player.pos.z);this.world.processQueue(1);this.updateMining(dt);this.updateEnvironment(dt);const ctx={playerPos:this.player.pos,dayLight:this.dayLight??1,inventory:this.inv,victory:!!this.worldData.victory,hurt:(n,r)=>this.hurt(n,r),explode:(p,r,d)=>this.explode(p,r,d),addXp:n=>this.addXp(n)};this.entities.update(dt,ctx);this.saveTimer+=dt;if(this.saveTimer>15){this.saveTimer=0;this.saveWorld();}this.updateHUD();this.updateDebug();}this.renderer.render(this.scene,this.camera);}
}

window.shardwildGame=new ShardwildGame();
